Update `slice_sample` in `dplyr_methods.R`
stemangiola/tidyseurat pull request #72
Opened 2023-08-31 06:43 UTC by noriakis

Hello, this PR clears the warning in `slice_sample`. I would be grateful if you could review the code.
Related to: https://github.com/stemangiola/tidySingleCellExperiment/pull/90

```
> data(pbmc_small)
> pbmc_small |> slice_sample(n=0)
Error: No cells found
```

2023-08-31 07:15 UTC, stemangiola requested changes
Amazing! 

Usually when we add a functionality, or fix an error/warning, we add a unit test, to test the changes.

For exmple if we solve an error, we would 

- first add a unit test (that would fail) to test that the error happens
- we then fix the error
- rerun the unit test expecting no error
- we commit the fix and the unit test

2023-08-31 07:55 UTC, noriakis commented
Thank you for your guidance! In this case, I added the unit test for `slice_sample()` expecting the error (`expect_error`). Would it be okay?

2023-08-31 11:48 UTC, merged

2023-10-30 03:17 UTC, stemangiola commented
Hello @wvictor14 @noriakis In the Seurat master, the slice functions produce errors in the tests. Could you please have a look?

Thanks!

2023-10-31 11:14 UTC, noriakis commented
Hello @stemangiola @wvictor14,

```r
expect_equal(
    pbmc_small |> as_tibble() |> arrange(nFeature_RNA) |> head(n = 5) %>% pull(.cell),
    pbmc_small |> slice_min(nFeature_RNA, n = 5) |> colnames()
)
```

The errors seem to come from above tests in `slice_min` and `slice_max`, where the `subset.Seurat` by cells returns the object that is preserving the original order of the cells. The returned row numbers of cells inside the function are correct, so one option would be to adding `sort()` to both vectors which removes the errors.

```r
expect_equal(
    pbmc_small |> as_tibble() |> arrange(nFeature_RNA) |> head(n = 5) %>% pull(.cell) |> sort(),
    pbmc_small |> slice_min(nFeature_RNA, n = 5) |> colnames() |> sort()
)
```
The `arrange()` function is currently deprecated, so maybe we could replace the test?

2023-10-31 11:38 UTC, stemangiola commented
> The `arrange()` function is currently deprecated, so maybe we could replace the test?

Agree, if you had the chance to do it, would be amazing.